#include "DdsCommonDataTypes.idl"
module com
{
module ulma
{
module supervisor
{
module dds
{
module agents
{
module lecturaModBusString
{
	//! Referencia unica de un agente: logicalDevice/logicalNode
   struct AgentReferenceType
   {
      //! Atributo propio
      //! Logical Device al que pertenece el agente.
      String ld;
      //! Atributo propio
      //! Logical Node del agente.
      String ln;
   };
   //! Estructura que define el contenido del topic LecturaModBusString
   struct LecturaModBusString
   {
      //! Atributo propio
      //! Id del dato
      AgentReferenceType src_id;

      //! Es la lectura
      String lectura;
	  
   };
   
      #pragma keylist LecturaModBusString src_id.ld src_id.ln
};  
};	  
};
};
};
};
